// 功法. kind 'cultivate' sets the cultivation multiplier; kind 'combat' adds to 戰力.

export const TECHS = {
  changchun: {
    name: '長春功',
    kind: 'cultivate',
    grade: '凡品',
    mult: 1.0,
    mindGuard: 0.1,
    desc: '最粗淺的吐納法門，勝在中正平和，不易走火入魔。',
  },
  qingmu: {
    name: '青木訣',
    kind: 'cultivate',
    grade: '黃品下',
    mult: 1.3,
    element: '木',
    elemBonus: 0.25,
    desc: '散修間流傳甚廣的木屬性功法。身具木靈根者修習，事半功倍。',
  },
  songhe: {
    name: '松鶴吐納術',
    kind: 'cultivate',
    grade: '黃品中',
    mult: 1.35,
    mindGuard: 0.35,
    desc: '松鶴道人一生修行的心血。重養心而輕求快，心魔難侵。',
  },
  lieyan: {
    name: '烈焰訣',
    kind: 'cultivate',
    grade: '黃品中',
    mult: 1.35,
    element: '火',
    elemBonus: 0.3,
    desc: '火屬性功法，進境快，脾氣也跟著變急。',
  },
  qingyun: {
    name: '青雲心法',
    kind: 'cultivate',
    grade: '黃品上',
    mult: 1.5,
    mindGuard: 0.15,
    desc: '青雲宗弟子人手一部的根本心法。',
  },
  xuanshui: {
    name: '玄水真經（殘）',
    kind: 'cultivate',
    grade: '玄品下',
    mult: 1.7,
    element: '水',
    elemBonus: 0.3,
    desc: '古戰場遺跡中得來的殘卷，只有前三層，卻遠勝坊間功法。',
  },
  qingyuan_sword: {
    name: '青元劍訣',
    kind: 'combat',
    grade: '黃品上',
    power: 0.35,
    desc: '山腹洞府中前輩留下的劍訣，一劍青光，三丈之內斬妖除魔。',
  },
  fox_fire: {
    name: '狐火術',
    kind: 'combat',
    grade: '黃品中',
    power: 0.25,
    desc: '胡三娘傳授的小法術，幽藍的狐火可灼魂魄。',
  },
  wild_boxing: {
    name: '莊稼把式',
    kind: 'combat',
    grade: '凡品',
    power: 0.05,
    desc: '鄉下人打架的本事，聊勝於無。',
  },
};
